{% set name = "napari-feature-classifier" %}
{% set version = "0.3.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 028417cce9d514846ca5d2a2a20dcba6b0d8aa3bc9dbb5b8e21bcc9da36ef759


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - imageio
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - pandera
    - python >={{ python_min }}
    - python-xxhash
    - qtpy
    - scikit-learn >=1.2.2
    - typing_extensions

test:
  imports:
    - napari_feature_classifier
    - napari_feature_classifier.classifier_widget
  commands:
    - pip list
    # - pip check  # Failds due to hypothesis
  requires:
    - python {{ python_min }}
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/fractal-napari-plugins-collection/napari-feature-classifier
  summary: An interactive classifier plugin to use with label images and feature measurements
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jluethi
