{% set name = "napari-feature-classifier" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-feature-classifier-{{ version }}.tar.gz
  sha256: 9d7171ee21a1f1cba7d810f4b05a07a2cf7bcc6587c888ab11a61b45d9a177b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imageio
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - pandera
    - python >=3.7
    - python-xxhash
    - qtpy
    - scikit-learn
    - typing_extensions

test:
  imports:
    - napari_feature_classifier
    - napari_feature_classifier.classifier_widget
  commands:
    - pip list
    # - pip check  # Failds due to hypothesis
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/fractal-napari-plugins-collection/napari-feature-classifier
  summary: An interactive classifier plugin to use with label images and feature measurements
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jluethi
