{% set name = "napari-feature-classifier" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dbf21b897216e9d9fcaa65b26b7f54b0c4aa6b1779b7b638584402adf147e6aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imageio
    - magicgui
    - matplotlib-base
    - napari <0.4.19
    - numpy <2.0
    - pandas
    - pandera <0.20.0
    - python >=3.7
    - python-xxhash
    - qtpy
    - scikit-learn >=1.2.2
    - typing_extensions

test:
  imports:
    - napari_feature_classifier
    - napari_feature_classifier.classifier_widget
  commands:
    - pip list
    # - pip check  # Failds due to hypothesis
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/fractal-napari-plugins-collection/napari-feature-classifier
  summary: An interactive classifier plugin to use with label images and feature measurements
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jluethi
