{% set name = "napari-feature-classifier" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4d9e4ca7fbc4c088afaacf4d376b28c444230827c8f0b14fe13cd36294da3c52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - imageio
    - magicgui
    - matplotlib-base
    - napari
    - numpy <2.0
    - pandas
    - pandera <0.20.0
    - python >={{ python_min }}
    - python-xxhash
    - qtpy
    - scikit-learn >=1.2.2
    - typing_extensions

test:
  imports:
    - napari_feature_classifier
    - napari_feature_classifier.classifier_widget
  commands:
    - pip list
    # - pip check  # Failds due to hypothesis
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/fractal-napari-plugins-collection/napari-feature-classifier
  summary: An interactive classifier plugin to use with label images and feature measurements
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jluethi
