{% set name = "napari-feature-classifier" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-feature-classifier-{{ version }}.tar.gz
  sha256: c4d97444911ddc5b6992bfe3d458527fa28dad861c5a6f14791bff4075d2ee0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imageio
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas
    - pandera
    - python >=3.7
    - python-xxhash
    - qtpy
    - scikit-learn
    - typing_extensions

test:
  imports:
    - napari_feature_classifier
    - napari_feature_classifier.classifier_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/fractal-napari-plugins-collection/napari-feature-classifier
  summary: An interactive classifier plugin to use with label images and feature measurements
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jluethi
